version: '3.8'
services:
  website-production:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: mm-air
    environment:  
      TZ: Asia/Bangkok
    ports:
      - "3000:3000"
    # volumes:
    #   - website_data:/app/data
    #   - node_modules:/app/node_modules
    restart: unless-stopped
    env_file:
      - .env.prod  
    networks:
      - main-network

# volumes:
#   website_data:
#   node_modules:

networks:
  main-network:
    external: true